[tool.poetry]
name = "phoenix-postgres-app"
version = "0.1.0"
description = ""
authors = ["Amit Prabhu <amit.dp180@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["standard"], version = "^0.115.0"}
pytest-asyncio = "^0.24.0"
# application-sdk = { path = "../application-sdk/", develop = true }
application-sdk = {git = "git@github.com:atlanhq/application-sdk.git", rev = "main"}
dash = "^2.18.1"
dash-bootstrap-components = "^1.6.0"
dash-ag-grid = "^31.2.0"
dash-dangerously-set-inner-html = "^0.0.2"
pandas = "^2.2.3"
pygwalker = "^0.4.9.10"

[tool.poetry.group.app.dependencies]
temporalio = "^1.7.0"
psycopg2-binary = "^2.9.9"
aiofiles = "^24.1.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.35"}


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"
isort = "^5.13.2"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"
coverage = "^7.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "strict"
reportMissingTypeStubs = false

[tool.pytest.ini_options]
asyncio_mode = "auto"

