[tool.poetry]
name = "phoenix-postgres-app"
version = "0.1.0"
description = ""
authors = ["Amit Prabhu <amit.dp180@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["standard"], version = "^0.113.0"}
pytest-asyncio = "^0.24.0"


[tool.poetry.group.sdk]
optional = false

[tool.poetry.group.sdk.dependencies]
fastapi-sqlalchemy = "^0.2.1"
alembic = "^1.13.2"
opentelemetry-distro = "^0.48b0"
opentelemetry-exporter-otlp = "^1.27.0"
opentelemetry-proto = "^1.27.0"
opentelemetry-instrumentation-fastapi = "^0.48b0"
psutil = "^6.0.0"
dapr = "^1.14.0"


[tool.poetry.group.app.dependencies]
temporalio = "^1.7.0"
psycopg2-binary = "^2.9.9"
aiofiles = "^24.1.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.35"}
asyncpg = "^0.29.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"
coverage = "^7.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "strict"

[tool.pytest.ini_options]
asyncio_mode = "auto"

