name: Publish Docker Image

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**'
      - '!kurl-installer.yaml'
      - '!**.md'
      - '!images/**'
      - '!**.png'

jobs:
  build:
    runs-on: [self-hosted, phoenix]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: get_branch

      - run: echo "REPOSITORY_NAME=`echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"`" >> $GITHUB_ENV
        shell: bash

      - name: Get version tag
        run: echo "version=$(echo `git ls-remote https://${{ secrets.ORG_PAT_GITHUB }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ steps.get_branch.outputs.branch }} | awk '{ print $1}' | cut -c1-7`)abcd" >> $GITHUB_OUTPUT
        id: get_version

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor Registry
        run: |
          bash ./.github/scripts/registry-login.sh "${{ secrets.HARBOR_URL }}" '${{ secrets.HARBOR_USERNAME }}' "${{ secrets.HARBOR_PASSWORD }}"
        shell: bash

      - name: Build and push core docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.HARBOR_URL }}/applications/${{ github.event.repository.name }}:${{ steps.get_branch.outputs.branch }}-${{ steps.get_version.outputs.version }}
            ${{ secrets.HARBOR_URL }}/applications/${{ github.event.repository.name }}:${{ steps.get_branch.outputs.branch }}-latest
          secrets: |
            PRIVATE_REPO_ACCESS_TOKEN=${{ secrets.ORG_PAT_GITHUB }}
        env:
          DOCKER_CLIENT_TIMEOUT: 300
          COMPOSE_HTTP_TIMEOUT: 300
