name: Pre-commit Checks
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        #----------------------------------------------
        #  -----  install & configure poetry  -----
        #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1 https://github.com/snok/install-poetry/releases/tag/v1.4.1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

        #----------------------------------------------
        #       set up system git client for poetry
        #       known to be available only in poetry 2.1.3
        #----------------------------------------------
      - name: Set up system git client for poetry
        run: |
          poetry config system-git-client true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
          poetry install --no-root --without dev
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1 https://github.com/pre-commit/action/releases/tag/v3.0.1
