name: Conventional Commits Check

on:
  pull_request:
    types: [ opened, synchronize, labeled, reopened ]
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write
  actions: read
  security-events: write


jobs:
  docstring-coverage:
    uses: atlanhq/application-sdk/.github/workflows/commits.yaml@main