name: Docstring Coverage

on:
  pull_request:
    types: [ opened, synchronize, labeled ]
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write
  actions: read
  security-events: write


jobs:
  docstring-coverage:
    uses: atlanhq/application-sdk/.github/workflows/docstring-coverage.yaml@main
    with:
      package_name: "app"