name: Unit Tests with Coverage for PR

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Install poetry
        run: |
          pip install poetry

      - name: Run Tests with Coverage
        run: |
          poetry install
          poetry run coverage run -m pytest app
          poetry run coverage xml

      - name: Comment Coverage Report on PR
        uses: orgoro/coverage@v2.1
        with:
          coverageFile: coverage.xml